#!/bin/bash


echo "Generating gossimon binary packages"
make clean
rm -f CMakeCache.txt

COMPILER_CMAKE_FLAGS=
#if grep -q "CentOS" /etc/issue ; then
#	echo "On centos... need gcc44 (the default of 4.1 does not have -std=cxx-0 for g++"
#	COMPILER_CMAKE_FLAGS=" -D CMAKE_C_COMPILER=gcc44 -D CMAKE_CXX_COMPILER=g++44"
#fi

cmake $COMPILER_CMAKE_FLAGS -DCMAKE_INSTALL_PREFIX=/usr -DGOSSIMON_INSTALL_ETC=/etc .
make package

echo 
echo

if  grep -q "CentOS" /etc/issue  ; then
    echo "Fixes for rpm generation on centos (problem in cpack)"
    ARC=`uname -m`
    ORIG_RPM=`ls *_Linux.rpm`
    if [ -e "$ORIG_RPM" ] ; then 
        echo "Found [$ORIG_RPM]"
        FIXED_RPM=${ORIG_RPM/_Linux.rpm/_$ARC.rpm}
        echo "Fixed: [$FIXED_RPM]"
        mv -f $ORIG_RPM $FIXED_RPM
    else
        echo "NO bad rpm found"
    fi
    
fi

exit 0



