#!/bin/bash

VERSION=$1
HOST=${2:-"oraion"}


echo "\$HOST is $HOST"
echo "Version to tag: $VERSION"
echo 
echo "Press any key to continue "
read

echo "Tagging trunk as version $VERSION"

svn copy svn+ssh://$HOST/opt/repos/gossimon/trunk svn+ssh://$HOST/opt/repos/gossimon/tags/release-$VERSION
