/*============================================================================
  gossimon - Gossip based resource usage monitoring for Linux clusters
  Copyright 2003-2010 Amnon Barak

  Distributed under the OSI-approved BSD License (the "License");
  see accompanying file Copyright.txt for details.

  This software is distributed WITHOUT ANY WARRANTY; without even the
  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
  See the License for more information.
============================================================================*/


#include <stdio.h>
#include <stdlib.h>

#include "parse_helper.h"
#include "mmon.h"

int displayFileSave(char *name, char **displayStrArr, int num) {

  FILE* f = fopen(name, "w");
  if(!f) {
    fprintf(stderr, "Error opening %s for writing\n", name);
    return 0;
  }

  fprintf(f, 
          "# MMON display save file\n"
          "# This file was automatically generated by mmon\n"
          "#\n"
          "# Do not edit this file manually unless you are absolutely sure\n"
          "# you know what you are doing\n"
          "\n\n"
          );
  for(int i=0 ; i < num ; i++)  {
    fprintf(f, "display %d: %s \n\n", i+1, displayStrArr[i]);
  }
  fclose(f);
  return 1;

}


int displayFileLoad(char *name, char **displayStrArr, int *num) {

     //int maxLines = *num;

  FILE* f = fopen(name, "r");
  if(!f) {
    fprintf(stderr, "\n\rNote: Could not open [%s] for reading -- not loading saved config\n", name);
    return 0;
  }
  
  char buff[1024];
  
  int dispNum = 0;
  while(fgets(buff, 1023, f)) {
      
       char *tmp = eat_spaces(buff);
       trim_spaces(tmp);
       if(tmp[0] == '#') 
            continue;
       
       if(strlen(tmp) == 0)
            continue;
       
       
       printf("Line:!%s!\n", tmp);
       //char spaces[100];
       //int  display;
       if(strncmp(tmp, "display", 7) == 0) {
            printf("Detected display line format\n");
            while(*tmp != ':' && *tmp != '\0') tmp++;
            if(*tmp == '\0') {
                 fprintf(stderr, "File is not in correct format\n");
                 return 0;
            }
            displayStrArr[dispNum++] = strdup(tmp);
       }
  }
  *num = dispNum;
  return 1;
}
