#!/bin/bash

usage() {
	echo "Usage: proc-num program-name [program-args]"
	echo
	echo "  $0 will run proc-num copies of program-name in the background,"
	echo "  where each copy will be given the program-args is any"	
}

if [ $# -eq 0 ] ; then usage && exit 1 ;  fi


if [ $# -eq 0 -o $1 == "-h" -o $1 == "--help" ] ; then
	usage
	exit 0
fi


if [ $# -lt 2 ] ; 
then
	echo "Usage: $0 proc-num program-name [program-args]"
	exit 1
fi

PROC_NUM=$1
shift

if [ $PROC_NUM -lt 1 ] ; then
	echo "Number of processes must be > 0"
	exit 1;
fi

for (( i=0 ; i<$PROC_NUM ; i++ )) 
do
	$@ &
done

